kanonbot.token=INSERT BOT TOKEN HERE
kanonbot.prefix=-
kanonbot.lavaname=kanon-node
kanonbot.lavauri=ws://localhost:2333
kanonbot.lavapass=INSERT PASSWORD
spring.datasource.url=jdbc:h2:file:./data/kanonbot;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
